<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; CHARSET=gb2312">
  <title>异常</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link media="all" rel="stylesheet" type="text/css" href="style.css"/>
 </head>
 <body class="docs" class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="language.errors.php7.html">? PHP 7 错误处理</a></li>
      <li style="float: right;"><a href="language.exceptions.extending.html">扩展（extend）异常处理类 ?</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="langref.html">语言参考</a></li>
    <li>异常</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="language.exceptions" class="chapter">
 <h1 class="title">异常</h1>
<h2>Table of Contents</h2><ul class="chunklist chunklist_chapter"><li><a href="language.exceptions.extending.html">扩展（extend）异常处理类</a></li></ul>

 <p class="para">
  PHP 有一个和其他语言相似的异常模型。在 PHP 里可以 <a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> 并捕获（<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>）异常。为了捕获潜在的异常，代码会包含在
  <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> 块里。每个 <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> 都必须至少有一个相应的 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 或 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 块。
 </p>
 <p class="para">
  如果抛出异常的函数作用域内没有 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 块，异常会沿调用栈"向上冒泡"，直到找到匹配的 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 块。沿途会执行所有遇到的
  <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 块。在没有设置全局异常处理程序时，如果调用栈向上都没有遇到匹配的 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>，程序会抛出 fatal 错误并终止。
 </p>
 <p class="para">
  抛出的对象必须是 <a href="language.operators.type.html" class="link"><code class="literal">instanceof</code></a> <span class="interfacename"><a href="class.throwable.html" class="interfacename">Throwable</a></span>。尝试抛出其他对象会导致 PHP Fatal 错误。
 </p>
 <p class="para">
  PHP 8.0.0 起，<a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> 关键词现在开始是表达式，可用于任何表达式上下文。在此之前，它是语句，必须独占一行。
 </p>

  <div id="language.exceptions.catch" class="sect1">
   <h2 class="title"><code class="literal">catch</code></h2>
   <p class="para">
    <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 定义了处理抛出异常的方式。
    <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 块定义了它能处理的异常/错误的类型，并可以选择将异常赋值到变量中。
    （在 PHP 8.0.0 之前的版本中必须要赋值到变量）
    如果遇到抛出对象的类型匹配了首个 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 块的异常或错误，将会处理该对象。
   </p>
   <p class="para">
    可用多个 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 捕获不同的异常类。
    正常情况下（<a href="language.exceptions.html" class="link"><code class="literal">try</code></a> 代码块里没有抛出异常）会在最后一个定义的 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 后面继续执行。
    <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 代码块里也可以 <a href="language.exceptions.html" class="link"><code class="literal">throw</code></a> 或者重新抛出异常。
    不抛出的话，会在触发的 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 后面继续执行。
   </p>
   <p class="para">
    当 PHP 抛出一个异常时，将不会执行后续的代码语句，并会尝试查找首个匹配的 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 代码块。
    如果没有用 <span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span> 设置异常处理函数，
    PHP 会在异常未被捕获时产生 Fatal 级错误，提示 &quot;<code class="literal">Uncaught Exception ...</code>&quot;
    消息。
   </p>
   <p class="para">
    从 PHP 7.1.0 起 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 可以用竖线符（<code class="literal">|</code>） 指定多个异常。
    如果在不同的类层次结构中，不同异常的异常需要用同样的方式处理，就特别适用这种方式。
   </p>
   <p class="para">
    从 PHP 8.0.0 起，捕获的异常不再强制要求指定变量名。
    <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 代码块会在未指定时继续执行，只是无法访问到抛出的对象。
   </p>
  </div>

  <div id="language.exceptions.finally" class="sect1">
   <h2 class="title"><code class="literal">finally</code></h2>
   <p class="para">
    <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 代码块可以放在 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 之后，或者直接代替它。 
    无论是否抛出了异常，在 <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> 和 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 之后、在执行后续代码之前，
    放在 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 里的代码总是会执行。
   </p>
   <p class="para">
    值得注意的是 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 和 <a href="function.return.html" class="link"><code class="literal">return</code></a> 语句之间存在相互影响。
    如果在 <a href="language.exceptions.html" class="link"><code class="literal">try</code></a> 或 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 里遇到 <a href="function.return.html" class="link"><code class="literal">return</code></a>，仍然会执行 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 里的代码。
    而且，遇到 <a href="function.return.html" class="link"><code class="literal">return</code></a> 语句时，会先执行 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 再返回结果。
    此外，如果 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 里也包含了 <a href="function.return.html" class="link"><code class="literal">return</code></a> 语句，将返回 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 里的值。
   </p>
  </div>

 <div id="language.exceptions.exception-handler" class="sect1">
  <h2 class="title">全局异常处理程序</h2>
  <p class="para">
   当允许异常冒泡到全局作用域时，它可以被全局异常处理器捕获到。
   <span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span> 
   可以设置一个函数，在没有调用其他块时代替 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>。
   在本质上，实现的效果等同于整个程序被 <a href="language.exceptions.html" class="link"><code class="literal">try</code></a>-<a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a> 包裹起来，
   而该函数就是 <a href="language.exceptions.html#language.exceptions.catch" class="link"><code class="literal">catch</code></a>。
  </p>
 </div>

 <div id="language.exceptions.notes" class="sect1">
   <h2 class="title">注释</h2>

   <blockquote class="note"><p><strong class="note">Note</strong>: 
    <p class="para">
     PHP 内部函数主要使用 <a href="errorfunc.configuration.html#ini.error-reporting" class="link">错误报告</a>，
     只有一些现代 <a href="language.oop5.html" class="link">面向对象</a> 的扩展使用异常。
     不过，错误很容易用 <a href="class.errorexception.html" class="link">ErrorException</a>
     转化成异常。
     然而，这个技术方案仅适用非 Fatal 级的错误。
    </p>
    <div class="example" id="example-322">
     <p><strong>Example #1 将错误报告转成异常</strong></p>
     <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function </span><span style="color: #0000BB">exceptions_error_handler</span><span style="color: #007700">(</span><span style="color: #0000BB">$severity</span><span style="color: #007700">, </span><span style="color: #0000BB">$message</span><span style="color: #007700">, </span><span style="color: #0000BB">$filename</span><span style="color: #007700">, </span><span style="color: #0000BB">$lineno</span><span style="color: #007700">) {<br />    throw new </span><span style="color: #0000BB">ErrorException</span><span style="color: #007700">(</span><span style="color: #0000BB">$message</span><span style="color: #007700">, </span><span style="color: #0000BB">0</span><span style="color: #007700">, </span><span style="color: #0000BB">$severity</span><span style="color: #007700">, </span><span style="color: #0000BB">$filename</span><span style="color: #007700">, </span><span style="color: #0000BB">$lineno</span><span style="color: #007700">);<br />}<br /><br /></span><span style="color: #0000BB">set_error_handler</span><span style="color: #007700">(</span><span style="color: #DD0000">'exceptions_error_handler'</span><span style="color: #007700">);<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
     </div>

    </div>
   </p></blockquote>
   <div class="tip"><strong class="tip">Tip</strong>
    <p class="para">
     <a href="intro.spl.html" class="link">PHP 标准库（SPL）</a> 
     提供了大量的 <a href="spl.exceptions.html" class="link">标准内置异常</a>。
    </p>
   </div>
 </div>

  <div id="language.exceptions.examples" class="sect1">
   <h2 class="title">示例</h2>

   <div class="example" id="example-323">
    <p><strong>Example #2 抛出一个异常</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">) {<br />    if (!</span><span style="color: #0000BB">$x</span><span style="color: #007700">) {<br />        throw new </span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Division by zero.'</span><span style="color: #007700">);<br />    }<br />    return </span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try {<br />    echo </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">) . </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />    echo </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">) . </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />    echo </span><span style="color: #DD0000">'Caught exception: '</span><span style="color: #007700">,  </span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(), </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">// 继续执行<br /></span><span style="color: #007700">echo </span><span style="color: #DD0000">"Hello World\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
    </div>

    <div class="example-contents"><p>以上示例会输出：</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
0.2
Caught exception: Division by zero.
Hello World
</pre></div>
    </div>
   </div>
   <div class="example" id="example-324">
    <p><strong>Example #3 带 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 块的异常处理</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">) {<br />    if (!</span><span style="color: #0000BB">$x</span><span style="color: #007700">) {<br />        throw new </span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Division by zero.'</span><span style="color: #007700">);<br />    }<br />    return </span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try {<br />    echo </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">) . </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />    echo </span><span style="color: #DD0000">'Caught exception: '</span><span style="color: #007700">,  </span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(), </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} finally {<br />    echo </span><span style="color: #DD0000">"First finally.\n"</span><span style="color: #007700">;<br />}<br /><br />try {<br />    echo </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">) . </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />    echo </span><span style="color: #DD0000">'Caught exception: '</span><span style="color: #007700">,  </span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(), </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} finally {<br />    echo </span><span style="color: #DD0000">"Second finally.\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">// 继续执行<br /></span><span style="color: #007700">echo </span><span style="color: #DD0000">"Hello World\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
    </div>

    <div class="example-contents"><p>以上示例会输出：</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
0.2
First finally.
Caught exception: Division by zero.
Second finally.
Hello World
</pre></div>
    </div>
   </div>
   <div class="example" id="example-325">
    <p><strong>Example #4 <a href="language.exceptions.html#language.exceptions.finally" class="link"><code class="literal">finally</code></a> 和 <a href="function.return.html" class="link"><code class="literal">return</code></a> 相互之间的影响</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">function </span><span style="color: #0000BB">test</span><span style="color: #007700">() {<br />    try {<br />        throw new </span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo'</span><span style="color: #007700">);<br />    } catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />        return </span><span style="color: #DD0000">'catch'</span><span style="color: #007700">;<br />    } finally {<br />        return </span><span style="color: #DD0000">'finally'</span><span style="color: #007700">;<br />    }<br />}<br /><br />echo </span><span style="color: #0000BB">test</span><span style="color: #007700">();<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
    </div>

    <div class="example-contents"><p>以上示例会输出：</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
finally
</pre></div>
    </div>
   </div>
   <div class="example" id="example-326">
    <p><strong>Example #5 异常嵌套</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class </span><span style="color: #0000BB">MyException </span><span style="color: #007700">extends </span><span style="color: #0000BB">Exception </span><span style="color: #007700">{ }<br /><br />class </span><span style="color: #0000BB">Test </span><span style="color: #007700">{<br />    public function </span><span style="color: #0000BB">testing</span><span style="color: #007700">() {<br />        try {<br />            try {<br />                throw new </span><span style="color: #0000BB">MyException</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo!'</span><span style="color: #007700">);<br />            } catch (</span><span style="color: #0000BB">MyException $e</span><span style="color: #007700">) {<br />                </span><span style="color: #FF8000">// 重新 throw<br />                </span><span style="color: #007700">throw </span><span style="color: #0000BB">$e</span><span style="color: #007700">;<br />            }<br />        } catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />            </span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">());<br />        }<br />    }<br />}<br /><br /></span><span style="color: #0000BB">$foo </span><span style="color: #007700">= new </span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br /><br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
    </div>

    <div class="example-contents"><p>以上示例会输出：</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
string(4) &quot;foo!&quot;
</pre></div>
    </div>
   </div>
   <div class="example" id="example-327">
    <p><strong>Example #6 多个异常的捕获处理</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class </span><span style="color: #0000BB">MyException </span><span style="color: #007700">extends </span><span style="color: #0000BB">Exception </span><span style="color: #007700">{ }<br /><br />class </span><span style="color: #0000BB">MyOtherException </span><span style="color: #007700">extends </span><span style="color: #0000BB">Exception </span><span style="color: #007700">{ }<br /><br />class </span><span style="color: #0000BB">Test </span><span style="color: #007700">{<br />    public function </span><span style="color: #0000BB">testing</span><span style="color: #007700">() {<br />        try {<br />            throw new </span><span style="color: #0000BB">MyException</span><span style="color: #007700">();<br />        } catch (</span><span style="color: #0000BB">MyException </span><span style="color: #007700">| </span><span style="color: #0000BB">MyOtherException $e</span><span style="color: #007700">) {<br />            </span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">get_class</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">));<br />        }<br />    }<br />}<br /><br /></span><span style="color: #0000BB">$foo </span><span style="color: #007700">= new </span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br /><br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
    </div>

    <div class="example-contents"><p>以上示例会输出：</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
string(11) &quot;MyException&quot;
</pre></div>
    </div>
   </div>
   <div class="example" id="example-328">
    <p><strong>Example #7 忽略捕获的变量</strong></p>
    <div class="example-contents"><p>仅仅在 PHP 8.0.0 及以上版本有效</p></div>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">function </span><span style="color: #0000BB">test</span><span style="color: #007700">() {<br />    throw new </span><span style="color: #0000BB">SpecificException</span><span style="color: #007700">(</span><span style="color: #DD0000">'Oopsie'</span><span style="color: #007700">);<br />}<br /><br />try {<br />    </span><span style="color: #0000BB">test</span><span style="color: #007700">();<br />} catch (</span><span style="color: #0000BB">SpecificException</span><span style="color: #007700">) {<br />    print </span><span style="color: #DD0000">"A SpecificException was thrown, but we don't care about the details."</span><span style="color: #007700">;<br />}<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
    </div>

   </div>
   <div class="example" id="example-329">
    <p><strong>Example #8 以表达式的形式抛出</strong></p>
    <div class="example-contents"><p>仅仅在 PHP 8.0.0 及以上版本有效</p></div>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class </span><span style="color: #0000BB">SpecificException </span><span style="color: #007700">extends </span><span style="color: #0000BB">Exception </span><span style="color: #007700">{}<br /><br />function </span><span style="color: #0000BB">test</span><span style="color: #007700">() {<br />    </span><span style="color: #0000BB">do_something_risky</span><span style="color: #007700">() or throw new </span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'It did not work'</span><span style="color: #007700">);<br />}<br /><br />try {<br />    </span><span style="color: #0000BB">test</span><span style="color: #007700">();<br />} catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />    print </span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">();<br />}<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
    </div>

   </div>
  </div>

 

 </div>
<div id="usernotes">
 <div class="head">
  <h3 class="title">User Contributed Notes</h3>
 </div>
<div id="allnotes">  <a name="129177""></a>
  <div class="note">
   <strong class="user">jlherren</strong>
   <a href="#129177" class="date">19-Jan-2024 08:24</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
As noted elsewhere, throwing an exception from the `finally` block will replace a previously thrown exception. But the original exception is magically available from the new exception's `getPrevious()`.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try {<br />
&nbsp;&nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">RuntimeException</span><span class="keyword">(</span><span class="string">'Exception A'</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; } finally {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">RuntimeException</span><span class="keyword">(</span><span class="string">'Exception B'</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
catch (</span><span class="default">Throwable $exception</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">(), </span><span class="string">"\n"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// 'previous' is magically available!<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">echo </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">(), </span><span class="string">"\n"</span><span class="keyword">;<br />
}<br />
</span><span class="default">?&gt;<br />
</span><br />
Will print:<br />
<br />
Exception B<br />
Exception A</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="128869""></a>
  <div class="note">
   <strong class="user">tianyiw at vip dot qq dot com</strong>
   <a href="#128869" class="date">08-Sep-2023 03:11</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Easy to understand `finally`.<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try {<br />
&nbsp;&nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"before\n"</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">1 </span><span class="keyword">/ </span><span class="default">0</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"after\n"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; } finally {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"finally\n"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
} catch (</span><span class="default">\Throwable</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"exception\n"</span><span class="keyword">;<br />
}<br />
</span><span class="default">?&gt;<br />
</span># Print:<br />
before<br />
finally<br />
exception</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="122434""></a>
  <div class="note">
   <strong class="user">mlaopane at gmail dot com</strong>
   <a href="#122434" class="date">24-Feb-2018 09:49</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
<span class="default">&lt;?php<br />
<br />
</span><span class="comment">/**<br />
&nbsp;* You can catch exceptions thrown in a deep level function<br />
&nbsp;*/<br />
<br />
</span><span class="keyword">function </span><span class="default">employee</span><span class="keyword">()<br />
{<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">\Exception</span><span class="keyword">(</span><span class="string">"I am just an employee !"</span><span class="keyword">);<br />
}<br />
<br />
function </span><span class="default">manager</span><span class="keyword">()<br />
{<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">employee</span><span class="keyword">();<br />
}<br />
<br />
function </span><span class="default">boss</span><span class="keyword">()<br />
{<br />
&nbsp;&nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">manager</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; } catch (</span><span class="default">\Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
</span><span class="default">boss</span><span class="keyword">(); </span><span class="comment">// output: "I am just an employee !"</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="121673""></a>
  <div class="note">
   <strong class="user">daviddlowe dot flimm at gmail dot com</strong>
   <a href="#121673" class="date">22-Sep-2017 01:13</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Starting in PHP 7, the classes Exception and Error both implement the Throwable interface. This means, if you want to catch both Error instances and Exception instances, you should catch Throwable objects, like this:<br />
<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="keyword">try {<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">Error</span><span class="keyword">( </span><span class="string">"foobar" </span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// or:<br />
&nbsp;&nbsp;&nbsp; // throw new Exception( "foobar" );<br />
</span><span class="keyword">}<br />
catch (</span><span class="default">Throwable $e</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">var_export</span><span class="keyword">( </span><span class="default">$e </span><span class="keyword">);<br />
}<br />
<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="121228""></a>
  <div class="note">
   <strong class="user">christof+php[AT]insypro.com</strong>
   <a href="#121228" class="date">15-Jun-2017 10:12</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
In case your E_WARNING type of errors aren't catchable with try/catch you can change them to another type of error like this:<br />
<br />
<span class="default">&lt;?php <br />
&nbsp;&nbsp;&nbsp; set_error_handler</span><span class="keyword">(function(</span><span class="default">$errno</span><span class="keyword">, </span><span class="default">$errstr</span><span class="keyword">, </span><span class="default">$errfile</span><span class="keyword">, </span><span class="default">$errline</span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; if(</span><span class="default">$errno </span><span class="keyword">=== </span><span class="default">E_WARNING</span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// make it more serious than a warning so it can be caught<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">trigger_error</span><span class="keyword">(</span><span class="default">$errstr</span><span class="keyword">, </span><span class="default">E_ERROR</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; return </span><span class="default">true</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; } else {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// fallback to default php error handler<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="keyword">return </span><span class="default">false</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; });<br />
<br />
&nbsp;&nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// code that might result in a E_WARNING<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">} catch(</span><span class="default">Exception $e</span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// code to handle the E_WARNING (it's actually changed to E_ERROR at this point)<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">} finally {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">restore_error_handler</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; }<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="117029""></a>
  <div class="note">
   <strong class="user">Simo</strong>
   <a href="#117029" class="date">04-Apr-2015 02:47</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
#3 is not a good example. inverse("0a") would not be caught since (bool) "0a" returns true, yet 1/"0a" casts the string to integer zero and attempts to perform the calculation.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="116273""></a>
  <div class="note">
   <strong class="user">Tom Polomsk</strong>
   <a href="#116273" class="date">04-Dec-2014 01:45</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Contrary to the documentation it is possible in PHP 5.5 and higher use only try-finally blocks without any catch block.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="115240""></a>
  <div class="note">
   <strong class="user">telefoontoestel at nospam dot org</strong>
   <a href="#115240" class="date">18-Jun-2014 12:34</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
When using finally keep in mind that when a exit/die statement is used in the catch block it will NOT go through the finally block. <br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"try block&lt;br /&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"test"</span><span class="keyword">);<br />
} catch (</span><span class="default">Exception $ex</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"catch block&lt;br /&gt;"</span><span class="keyword">;<br />
} finally {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"finally block&lt;br /&gt;"</span><span class="keyword">;<br />
}<br />
<br />
</span><span class="comment">// try block<br />
// catch block<br />
// finally block<br />
</span><span class="default">?&gt;<br />
</span><br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"try block&lt;br /&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"test"</span><span class="keyword">);<br />
} catch (</span><span class="default">Exception $ex</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"catch block&lt;br /&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; exit(</span><span class="default">1</span><span class="keyword">);<br />
} finally {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"finally block&lt;br /&gt;"</span><span class="keyword">;<br />
}<br />
<br />
</span><span class="comment">// try block<br />
// catch block<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="112507""></a>
  <div class="note">
   <strong class="user">Edu</strong>
   <a href="#112507" class="date">24-Jun-2013 06:13</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
The "finally" block can change the exception that has been throw by the catch block.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try{<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">\Exception</span><span class="keyword">(</span><span class="string">"Hello"</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; } catch(</span><span class="default">\Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" catch in\n"</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw </span><span class="default">$e</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; } finally {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" finally \n"</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">\Exception</span><span class="keyword">(</span><span class="string">"Bye"</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
} catch (</span><span class="default">\Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" catch out\n"</span><span class="keyword">;<br />
}<br />
</span><span class="default">?&gt;<br />
</span><br />
The output is:<br />
<br />
Hello catch in<br />
Hello finally <br />
Bye catch out</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="106696""></a>
  <div class="note">
   <strong class="user">Sawsan</strong>
   <a href="#106696" class="date">28-Nov-2011 09:36</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
the following is an example of a re-thrown exception and the using of getPrevious function:<br />
<br />
<span class="default">&lt;?php<br />
<br />
$name </span><span class="keyword">= </span><span class="string">"Name"</span><span class="keyword">;<br />
<br />
</span><span class="comment">//check if the name contains only letters, and does not contain the word name<br />
<br />
</span><span class="keyword">try<br />
&nbsp;&nbsp; {<br />
&nbsp;&nbsp; try<br />
&nbsp;&nbsp; &nbsp; {<br />
&nbsp;&nbsp; &nbsp;&nbsp; if (</span><span class="default">preg_match</span><span class="keyword">(</span><span class="string">'/[^a-z]/i'</span><span class="keyword">, </span><span class="default">$name</span><span class="keyword">)) <br />
&nbsp;&nbsp; &nbsp; &nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"</span><span class="default">$name</span><span class="string"> contains character other than a-z A-Z"</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp; }&nbsp;&nbsp; <br />
&nbsp;&nbsp; &nbsp; &nbsp; if(</span><span class="default">strpos</span><span class="keyword">(</span><span class="default">strtolower</span><span class="keyword">(</span><span class="default">$name</span><span class="keyword">), </span><span class="string">'name'</span><span class="keyword">) !== </span><span class="default">FALSE</span><span class="keyword">)<br />
&nbsp;&nbsp; &nbsp; &nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"</span><span class="default">$name</span><span class="string"> contains the word name"</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp; }<br />
&nbsp;&nbsp; &nbsp; &nbsp; echo </span><span class="string">"The Name is valid"</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; }<br />
&nbsp;&nbsp; catch(</span><span class="default">Exception $e</span><span class="keyword">)<br />
&nbsp;&nbsp; &nbsp; {<br />
&nbsp;&nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"insert name again"</span><span class="keyword">,</span><span class="default">0</span><span class="keyword">,</span><span class="default">$e</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; }<br />
&nbsp;&nbsp; }<br />
&nbsp;<br />
catch (</span><span class="default">Exception $e</span><span class="keyword">)<br />
&nbsp;&nbsp; {<br />
&nbsp;&nbsp; if (</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">())<br />
&nbsp;&nbsp; {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"The Previous Exception is: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">"&lt;br/&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp; }<br />
&nbsp;&nbsp; echo </span><span class="string">"The Exception is: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">"&lt;br/&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp; }<br />
<br />
&nbsp;</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="103819""></a>
  <div class="note">
   <strong class="user">Johan</strong>
   <a href="#103819" class="date">05-May-2011 01:18</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Custom error handling on entire pages can avoid half rendered pages for the users:<br />
<br />
<span class="default">&lt;?php<br />
ob_start</span><span class="keyword">();<br />
try {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">/*contains all page logic <br />
&nbsp;&nbsp;&nbsp; and throws error if needed*/<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">...<br />
} catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp; </span><span class="default">ob_end_clean</span><span class="keyword">();<br />
&nbsp; </span><span class="default">displayErrorPage</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br />
}<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="91159""></a>
  <div class="note">
   <strong class="user">ask at nilpo dot com</strong>
   <a href="#91159" class="date">27-May-2009 12:19</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
If you intend on creating a lot of custom exceptions, you may find this code useful.&nbsp; I've created an interface and an abstract exception class that ensures that all parts of the built-in Exception class are preserved in child classes.&nbsp; It also properly pushes all information back to the parent constructor ensuring that nothing is lost.&nbsp; This allows you to quickly create new exceptions on the fly.&nbsp; It also overrides the default __toString method with a more thorough one.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">interface </span><span class="default">IException<br />
</span><span class="keyword">{<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">/* Protected methods inherited from Exception class */<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getMessage</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Exception message <br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getCode</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// User-defined Exception code<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getFile</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source filename<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getLine</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source line<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getTrace</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// An array of the backtrace()<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getTraceAsString</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Formated string of trace<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; /* Overrideable methods inherited from Exception class */<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">__toString</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// formated string for display<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">);<br />
}<br />
<br />
abstract class </span><span class="default">CustomException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">implements </span><span class="default">IException<br />
</span><span class="keyword">{<br />
&nbsp;&nbsp;&nbsp; protected </span><span class="default">$message </span><span class="keyword">= </span><span class="string">'Unknown exception'</span><span class="keyword">;&nbsp; &nbsp;&nbsp; </span><span class="comment">// Exception message<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">private&nbsp;&nbsp; </span><span class="default">$string</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Unknown<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">protected </span><span class="default">$code&nbsp; &nbsp; </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// User-defined exception code<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">protected </span><span class="default">$file</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source filename of exception<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">protected </span><span class="default">$line</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source line of exception<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">private&nbsp;&nbsp; </span><span class="default">$trace</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Unknown<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">)<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; if (!</span><span class="default">$message</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">$this</span><span class="keyword">(</span><span class="string">'Unknown '</span><span class="keyword">. </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">));<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">parent</span><span class="keyword">::</span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function </span><span class="default">__toString</span><span class="keyword">()<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">) . </span><span class="string">" '</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">message</span><span class="keyword">}</span><span class="string">' in </span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">file</span><span class="keyword">}</span><span class="string">(</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">line</span><span class="keyword">}</span><span class="string">)\n"<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="keyword">. </span><span class="string">"</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">()}</span><span class="string">"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
</span><span class="default">?&gt;<br />
</span><br />
Now you can create new exceptions in one line:<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">class </span><span class="default">TestException </span><span class="keyword">extends </span><span class="default">CustomException </span><span class="keyword">{}<br />
</span><span class="default">?&gt;<br />
</span><br />
Here's a test that shows that all information is properly preserved throughout the backtrace.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">function </span><span class="default">exceptionTest</span><span class="keyword">()<br />
{<br />
&nbsp;&nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">TestException</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; catch (</span><span class="default">TestException $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"Caught TestException ('</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">')\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"Caught Exception ('</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">')\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
echo </span><span class="string">'&lt;pre&gt;' </span><span class="keyword">. </span><span class="default">exceptionTest</span><span class="keyword">() . </span><span class="string">'&lt;/pre&gt;'</span><span class="keyword">;<br />
</span><span class="default">?&gt;<br />
</span><br />
Here's a sample output:<br />
<br />
Caught TestException ('Unknown TestException')<br />
TestException 'Unknown TestException' in C:\xampp\htdocs\CustomException\CustomException.php(31)<br />
#0 C:\xampp\htdocs\CustomException\ExceptionTest.php(19): CustomException-&gt;__construct()<br />
#1 C:\xampp\htdocs\CustomException\ExceptionTest.php(43): exceptionTest()<br />
#2 {main}</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="86476""></a>
  <div class="note">
   <strong class="user">Shot (Piotr Szotkowski)</strong>
   <a href="#86476" class="date">21-Oct-2008 12:13</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
'Normal execution (when no exception is thrown within the try block, *or when a catch matching the thrown exception's class is not present*) will continue after that last catch block defined in sequence.'<br />
<br />
'If an exception is not caught, a PHP Fatal Error will be issued with an "Uncaught Exception ..." message, unless a handler has been defined with set_exception_handler().'<br />
<br />
These two sentences seem a bit contradicting about what happens 'when a catch matching the thrown exception's class is not present' (and the second sentence is actually correct).</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
</div>
</div>
</div></div></body></html>
